Repository MediBird/caring-note-api-server, pull requests merged in 2025-03, with the labels that each got.

#137 feat: ✨ add CounseleeAutoComplete API
  src/main/java/com/springboot/api/counselee/controller/CounseleeController.java
  src/main/java/com/springboot/api/counselee/dto/SelectCounseleeAutocompleteRes.java
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryCustom.java
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java
  src/main/java/com/springboot/api/counselee/service/CounseleeService.java
  src/main/java/com/springboot/api/medication/repository/MedicationRepository.java
  src/test/java/com/springboot/api/controller/CounseleeAutocompleteControllerTest.java
  src/test/java/com/springboot/api/repository/CounseleeRepositoryTest.java
  src/test/java/com/springboot/api/service/CounseleeServiceTest.java
Labels: D-0

#139 Feature/ add, update CounselSession API
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/AddCounselSessionByCounseleeReq.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/UpdateStartTimeInCounselSessionReq.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java
  src/test/java/com/springboot/api/service/CounselSessionServiceTest.java
  src/test/java/com/springboot/api/service/CounseleeServiceTest.java
Labels: D-1

#140 refactor: ♻️ refactor the name of updateCounselSession
  src/main/java/com/springboot/api/counselee/service/CounseleeService.java
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/ModifyCounselReservationReq.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/ModifyCounselReservationRes.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/UpdateCounselSessionReq.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/UpdateCounselSessionRes.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java
  src/test/java/com/springboot/api/service/CounselSessionServiceTest.java
Labels: D-0

#141 fix: :wastebasket: delete deprecated annotation
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
Labels: D-0

#142 refactor: :recycle: refactor addCounselSession
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/AddCounselSessionByCounseleeReq.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/AddCounselSessionRes.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/CreateCounselReservationReq.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/CreateCounselReservationRes.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java
  src/test/java/com/springboot/api/service/CounselSessionServiceTest.java
Labels: D-0

#143 fix: :card_file_box: fix querydsl query
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java
Labels: D-0, D-3

#144 feat: :sparkles: add SessionNumber to CounselSession Entity
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-0

#145 refactor: :recycle: modify SelectCounselSessionRes
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionPageRes.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
Labels: D-0

#146 refactor: :recycle: refactor SelectCounselSessionRes
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
Labels: D-3

#149 feat: add @OnDelete and Fetch.LAZY, remove useless @OneToMany
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselee/entity/Counselee.java
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java
  src/main/java/com/springboot/api/counselor/entity/Counselor.java
  src/main/java/com/springboot/api/counselsession/entity/AICounselSummary.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/entity/CounseleeConsent.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounsel.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounselHighlight.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java
  src/main/java/com/springboot/api/counselsession/entity/PromptTemplate.java
  src/main/java/com/springboot/api/counselsession/entity/WasteMedicationDisposal.java
  src/main/java/com/springboot/api/counselsession/entity/WasteMedicationRecord.java
Labels: D-3

#150 refactor: CounselCardService package and update imports
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/test/java/com/springboot/api/controller/CounselCardControllerTest.java
Labels: D-3

#151 feat: :sparkles: add keycloak admin client library
  build.gradle
  src/main/java/com/springboot/api/counselor/config/KeycloakAdminClient.java
  src/main/java/com/springboot/api/counselor/controller/KeycloakUserController.java
  src/main/java/com/springboot/api/counselor/service/KeycloakUserService.java
  src/main/resources/application.yml
Labels: D-2

#152 feat: update name validation regex
  src/main/java/com/springboot/api/counselee/dto/AddCounseleeReq.java
Labels: D-2

#155 Refactor/stt ta service
  src/main/java/com/springboot/api/counselor/entity/Counselor.java
  src/main/java/com/springboot/api/counselsession/dto/aiCounselSummary/SelectSpeakerListRes.java
  src/main/java/com/springboot/api/counselsession/dto/naverClova/DiarizationDTO.java
  src/main/java/com/springboot/api/counselsession/service/AICounselSummaryService.java
  src/test/java/com/springboot/api/common/STTTest.java
  src/test/java/com/springboot/api/service/AICounselSummaryServiceTest.java
Labels: D-0

#156 Refactor/stt ta speaker filter
  src/main/java/com/springboot/api/counselsession/service/AICounselSummaryService.java
  src/test/java/com/springboot/api/common/STTTest.java
  src/test/java/com/springboot/api/service/AICounselSummaryServiceTest.java
Labels: D-0

#157 feat: ✨ add apis for counselor
  src/main/java/com/springboot/api/common/exception/ResourceNotFoundException.java
  src/main/java/com/springboot/api/counselor/controller/CounselorController.java
  src/main/java/com/springboot/api/counselor/dto/ResetPasswordReq.java
  src/main/java/com/springboot/api/counselor/dto/UpdateRoleReq.java
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
  src/main/java/com/springboot/api/counselor/service/KeycloakUserService.java
  src/test/java/com/springboot/api/common/STTTest.java
Labels: D-3

#158 feat: :sparkles: add description column and pagination apis
  src/main/java/com/springboot/api/counselor/controller/CounselorController.java
  src/main/java/com/springboot/api/counselor/controller/KeycloakUserController.java
  src/main/java/com/springboot/api/counselor/dto/CounselorPageRes.java
  src/main/java/com/springboot/api/counselor/entity/Counselor.java
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
Labels: D-3

#159 fix: fix SelectCounselSessionRes
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
Labels: D-0, D-3

#162 fix: :passport_control: modify permission of getMyInfo()
  src/main/java/com/springboot/api/counselor/controller/CounselorController.java
Labels: D-3

#164 Refactor/ta filter add recommend
  src/main/java/com/springboot/api/counselsession/dto/aiCounselSummary/SelectSpeakerListRes.java
  src/main/java/com/springboot/api/counselsession/dto/aiCounselSummary/SpeakerStatsDTO.java
  src/main/java/com/springboot/api/counselsession/service/AICounselSummaryService.java
  src/test/java/com/springboot/api/service/AICounselSummaryServiceTest.java
Labels: D-0

#165 Feature : add counsel card independentlife
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/CommunicationDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/EvacuationDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/WalkingDTO.java
  src/main/java/com/springboot/api/counselcard/dto/request/AddCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/AddDisabledCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateBaseInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateHealthInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateIndependentLifeInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateLivingInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardIdRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/TimeRecordedRes.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryCustom.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryImpl.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/main/java/com/springboot/enums/CommunicationType.java
  src/main/java/com/springboot/enums/CounselCardRecordType.java
  src/main/java/com/springboot/enums/EvacuationType.java
  src/main/java/com/springboot/enums/HearingType.java
  src/main/java/com/springboot/enums/SightType.java
  src/main/java/com/springboot/enums/UsingKoreanType.java
  src/main/java/com/springboot/enums/WalkingEquipmentType.java
  src/main/java/com/springboot/enums/WalkingType.java
Labels: D-3

#166 Revert "Feature : add counsel card independentlife"
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/dto/AddCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/CounselCardIdRes.java
  src/main/java/com/springboot/api/counselcard/dto/CounselCardRes.java
  src/main/java/com/springboot/api/counselcard/dto/TimeRecordedDTO.java
  src/main/java/com/springboot/api/counselcard/dto/UpdateCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/CommunicationDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/EvacuationDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/WalkingDTO.java
  src/main/java/com/springboot/api/counselcard/dto/request/AddDisabledCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateBaseInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateHealthInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateIndependentLifeInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateLivingInformationReq.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryCustom.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryImpl.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/main/java/com/springboot/enums/CommunicationType.java
  src/main/java/com/springboot/enums/CounselCardRecordType.java
  src/main/java/com/springboot/enums/EvacuationType.java
  src/main/java/com/springboot/enums/HearingType.java
  src/main/java/com/springboot/enums/SightType.java
  src/main/java/com/springboot/enums/UsingKoreanType.java
  src/main/java/com/springboot/enums/WalkingEquipmentType.java
  src/main/java/com/springboot/enums/WalkingType.java
Labels: D-3

#167 feature: counsel card
  src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/CommunicationDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/EvacuationDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/WalkingDTO.java
  src/main/java/com/springboot/api/counselcard/dto/request/AddCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/AddDisabledCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateBaseInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateCounselCardStatusReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateHealthInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateIndependentLifeInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateLivingInformationReq.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardBaseInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardHealthInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardIdRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardIndependentLifeInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardLivingInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/TimeRecordedRes.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCardFactory.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryCustom.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryImpl.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/main/java/com/springboot/enums/CommunicationType.java
  src/main/java/com/springboot/enums/CounselCardRecordType.java
  src/main/java/com/springboot/enums/EvacuationType.java
  src/main/java/com/springboot/enums/HearingType.java
  src/main/java/com/springboot/enums/SightType.java
  src/main/java/com/springboot/enums/UsingKoreanType.java
  src/main/java/com/springboot/enums/WalkingEquipmentType.java
  src/main/java/com/springboot/enums/WalkingType.java
Labels: D-3

#168 Refactor: counsel session status
  src/main/java/com/springboot/api/counselcard/dto/information/health/AllergyDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/health/MedicationSideEffectDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/DrinkingDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/SmokingDTO.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCardFactory.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionListItem.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/main/java/com/springboot/enums/CardRecordStatus.java
  src/main/java/com/springboot/enums/CommunicationType.java
  src/main/java/com/springboot/enums/DrinkingAmount.java
  src/main/java/com/springboot/enums/ScheduleStatus.java
  src/main/java/com/springboot/enums/SmokingAmount.java
Labels: D-3

#169 test: add mock for CounselCardService in CounselSessionServiceTest
  src/test/java/com/springboot/api/service/CounselSessionServiceTest.java
Labels: D-3

#170 refactor: :recycle: refactor MedicationManagement
  src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
Labels: D-3

#171 feat: :sparkles: add ElementCollection
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
Labels: D-3

#173 refactor: :recycle: refactor set to list
  src/main/java/com/springboot/api/counselcard/dto/information/base/CounselPurposeAndNoteDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/health/DiseaseInfoDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/EvacuationDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/independentlife/WalkingDTO.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
Labels: bug, D-0

#175 refactor: :recycle: refactor set to list
  src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
Labels: D-3

#177 refactor: :recycle: refactor entities
  src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java
  src/main/java/com/springboot/api/common/entity/BaseEntity.java
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/dto/information/health/DiseaseInfoDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/DrinkingDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/SmokingDTO.java
  src/main/java/com/springboot/api/counselcard/dto/request/AddCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardBaseInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardHealthInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardIndependentLifeInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardLivingInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/CounselCardRes.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryImpl.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/main/java/com/springboot/api/counselee/dto/AddCounseleeReq.java
  src/main/java/com/springboot/api/counselee/entity/Counselee.java
  src/main/java/com/springboot/api/counselee/service/CounseleeService.java
  src/main/java/com/springboot/api/counselsession/entity/AICounselSummary.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/entity/CounseleeConsent.java
  src/main/java/com/springboot/api/counselsession/entity/Medication.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounsel.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounselHighlight.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java
  src/main/java/com/springboot/api/counselsession/entity/PromptLearning.java
  src/main/java/com/springboot/api/counselsession/entity/PromptTemplate.java
  src/main/java/com/springboot/api/counselsession/entity/WasteMedicationDisposal.java
  src/main/java/com/springboot/api/counselsession/entity/WasteMedicationRecord.java
  src/main/java/com/springboot/api/counselsession/service/MedicationCounselService.java
  src/main/java/com/springboot/api/counselsession/service/MedicationRecordHistService.java
  src/main/java/com/springboot/api/counselsession/service/WasteMedicationDisposalService.java
  src/main/java/com/springboot/api/counselsession/service/WasteMedicationRecordService.java
  src/main/java/com/springboot/enums/DrinkingAmount.java
  src/main/java/com/springboot/enums/SmokingAmount.java
  src/test/java/com/springboot/api/controller/CounselCardControllerTest.java
  src/test/java/com/springboot/api/controller/CounseleeAutocompleteControllerTest.java
  src/test/java/com/springboot/api/controller/CounseleeConsentControllerTest.java
  src/test/java/com/springboot/api/repository/CounselCardRepositoryTest.java
  src/test/java/com/springboot/api/service/AICounselSummaryServiceTest.java
  src/test/java/com/springboot/api/service/MedicationServiceTest.java
Labels: D-0

#178 refactor: :bug: add NoArgsConstructor
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselee/entity/Counselee.java
  src/main/java/com/springboot/api/counselor/entity/Counselor.java
  src/main/java/com/springboot/api/counselsession/entity/AICounselSummary.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/entity/CounseleeConsent.java
  src/main/java/com/springboot/api/counselsession/entity/Medication.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounsel.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounselHighlight.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java
  src/main/java/com/springboot/api/counselsession/entity/PromptLearning.java
  src/main/java/com/springboot/api/counselsession/entity/PromptTemplate.java
  src/main/java/com/springboot/api/counselsession/entity/WasteMedicationDisposal.java
  src/main/java/com/springboot/api/counselsession/entity/WasteMedicationRecord.java
Labels: D-0, D-3

#179 refactor: :recycle: refactor CounselorService query
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepository.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryCustom.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryImpl.java
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
Labels: D-0

#181 refactor: update Allergy and MedicationSideEffect
  src/main/java/com/springboot/api/counselcard/dto/information/health/AllergyDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/health/MedicationSideEffectDTO.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
Labels: D-3

#182 refactor: :recycle: refactor counselor name logic
  src/main/java/com/springboot/api/common/converter/CustomJwtRoleConverter.java
Labels: D-3

#180 fix: counselee change
  src/main/java/com/springboot/api/counselee/service/CounseleeService.java
Labels: D-1

#185 refactor: :bug: add cacheEvict to UpdateCounselCardStatus
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
Labels: D-0

#186 Fix: stt file delete issue
  src/main/java/com/springboot/api/common/properties/SttFileProperties.java
  src/main/java/com/springboot/api/common/util/FileUtil.java
  src/main/java/com/springboot/api/counselsession/controller/AICounselSummaryController.java
  src/main/java/com/springboot/api/counselsession/service/AICounselSummaryService.java
  src/main/java/com/springboot/api/infra/external/NaverClovaExternalService.java
  src/test/java/com/springboot/api/common/FileUtilTest.java
  src/test/java/com/springboot/api/common/STTTest.java
Labels: D-3

#187 fix: :passport_control: refactor get counselor names
  src/main/java/com/springboot/api/counselor/repository/CounselorRepository.java
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
Labels: D-2

#189 Feature: soft delete on counselor
  src/main/java/com/springboot/api/counselor/entity/Counselor.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepository.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryCustom.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryImpl.java
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
  src/main/java/com/springboot/api/counselor/service/CounselorUserDetailsService.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-3

#190 refactor: :recycle: refactor AddAndUpdateMedicationRecordHistReq
  .gitignore
  src/main/java/com/springboot/api/counselsession/dto/medicationRecordHist/AddAndUpdateMedicationRecordHistReq.java
  src/main/java/com/springboot/api/counselsession/dto/medicationRecordHist/SelectMedicationRecordHistRes.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java
  src/main/java/com/springboot/api/counselsession/service/MedicationRecordHistService.java
Labels: bug, D-0

#191 fix: :bug: fix string to null date error
  src/main/java/com/springboot/api/counselsession/service/MedicationRecordHistService.java
Labels: D-3

#192 refactor: :safety_vest: remove validation from medicationId
  src/main/java/com/springboot/api/counselsession/dto/medicationRecordHist/AddAndUpdateMedicationRecordHistReq.java
Labels: D-3

#194 feat: add CounselCard Update API
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/dto/information/health/AllergyDTO.java
  src/main/java/com/springboot/api/counselcard/dto/request/UpdateCounselCardReq.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
Labels: D-3

#197 Fix : delete counselee bug
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselee/service/CounseleeService.java
Labels: D-3

#198 fix: :bug: fix update communication bug
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
Labels: bug, D-0

#201 Refactor: counsel card refactor
  src/main/java/com/springboot/api/common/annotation/ValidNullableEnum.java
  src/main/java/com/springboot/api/common/validator/NullableEnumValidator.java
  src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java
  src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/api/counselee/dto/UpdateCounseleeReq.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-3

#202 Refactor/file upload improve
  Dockerfile
  src/main/resources/application.yml
Labels: D-0
