Repository MediBird/caring-note-api-server, pull requests merged in 2025-04, with the labels that each got.

#203 refactor: move Medication entity to medication package
  src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java
  src/main/java/com/springboot/api/counselsession/entity/WasteMedicationRecord.java
  src/main/java/com/springboot/api/medication/entity/Medication.java
  src/main/java/com/springboot/api/medication/repository/MedicationRepository.java
  src/test/java/com/springboot/api/service/MedicationServiceTest.java
Labels: D-3

#204 Refactor/integrate stt ta
  src/main/java/com/springboot/api/counselsession/controller/AICounselSummaryController.java
  src/main/java/com/springboot/api/counselsession/dto/aiCounselSummary/AnalyseTextReq.java
  src/main/java/com/springboot/api/counselsession/service/AICounselSummaryService.java
  src/main/java/com/springboot/api/counselsession/service/eventlistener/STTCompleteEvent.java
  src/main/java/com/springboot/api/counselsession/service/eventlistener/STTCompleteEventListener.java
  src/test/java/com/springboot/api/service/AICounselSummaryServiceTest.java
Labels: D-1

#205 Refactor: counselee 리팩토링 및 테스트 픽스처 추가
  build.gradle
  src/main/java/com/springboot/api/counselee/dto/UpdateCounseleeReq.java
  src/main/java/com/springboot/api/counselee/entity/Counselee.java
  src/main/java/com/springboot/api/counselee/service/CounseleeService.java
  src/test/java/com/springboot/api/controller/CounseleeControllerTest.java
  src/test/java/com/springboot/api/fixture/CounseleeFixture.java
  src/test/java/com/springboot/api/fixture/FixtureRandomUtil.java
  src/test/java/com/springboot/api/service/CounseleeServiceTest.java
Labels: D-3

#206 refactor: add JPA table annotation to Counselee entity
  src/main/java/com/springboot/api/counselee/entity/Counselee.java
Labels: D-3

#208 feature: remove check disability info
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
Labels: D-3

#209 refactor: resize tab size in couselsession service
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-3

#210 Feature: counsel session num
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselsession/entity/CounselSession.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepository.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-3

#212 refactor: update counsel card column nullable
  src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java
  src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
Labels: D-3

#211 feat: :memo: add cursor rules
  .cursor/rules/ spring-security-rules.mdc
  .cursor/rules/code-review-checklist.mdc
  .cursor/rules/entity-class-conventions.mdc
  .cursor/rules/java-development-practices.mdc
  .cursor/rules/spring-boot-project-rules.mdc
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/main/java/com/springboot/api/counselsession/dto/medicationcounsel/AddMedicationCounselReq.java
  src/main/java/com/springboot/api/counselsession/dto/medicationcounsel/SelectMedicationCounselRes.java
  src/main/java/com/springboot/api/counselsession/dto/medicationcounsel/SelectPreviousMedicationCounselRes.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounsel.java
  src/main/java/com/springboot/api/counselsession/entity/MedicationCounselHighlight.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepository.java
  src/main/java/com/springboot/api/counselsession/repository/MedicationCounselHighlightRepository.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/main/java/com/springboot/api/counselsession/service/MedicationCounselService.java
  src/main/java/com/springboot/api/medication/repository/MedicationRepository.java
  src/main/java/com/springboot/api/medication/repository/MedicationRepositoryCustom.java
  src/main/java/com/springboot/api/medication/repository/MedicationRepositoryCustomImpl.java
  src/main/java/com/springboot/api/medication/service/MedicationService.java
  src/test/java/com/springboot/api/service/MedicationServiceTest.java
Labels: D-1

#215 fix: :fire: remove counselor validation logic
  src/main/java/com/springboot/api/counselee/controller/CounseleeController.java
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-3

#221 refactor: ✨ add common pagination entity
  src/main/java/com/springboot/api/common/dto/PageReq.java
  src/main/java/com/springboot/api/common/dto/PageRes.java
  src/main/java/com/springboot/api/common/util/QuerydslPagingUtil.java
  src/main/java/com/springboot/api/counselee/controller/CounseleeController.java
  src/main/java/com/springboot/api/counselee/dto/SelectCounseleePageRes.java
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryCustom.java
  src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java
  src/main/java/com/springboot/api/counselee/service/CounseleeService.java
  src/main/java/com/springboot/api/counselor/controller/CounselorController.java
  src/main/java/com/springboot/api/counselor/dto/CounselorInfoListRes.java
  src/main/java/com/springboot/api/counselor/dto/CounselorPageRes.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryCustom.java
  src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryImpl.java
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
  src/main/java/com/springboot/api/counselsession/controller/CounseleeConsentController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SearchCounselSessionReq.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionListByBaseDateAndCursorAndSizeReq.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionPageRes.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/main/java/com/springboot/api/counselsession/service/CounseleeConsentService.java
  src/test/java/com/springboot/api/controller/CounseleeControllerTest.java
Labels: D-3

#226 refactor: remove deprecated
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselsession/controller/AICounselSummaryController.java
  src/main/resources/application.yml
  src/test/java/com/springboot/api/controller/CounselCardControllerTest.java
Labels: D-3

#229 feat: add new columns and inputs to the counselcard
  build.gradle
  src/main/java/com/springboot/api/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java
  src/main/java/com/springboot/api/counselcard/dto/information/living/NutritionDTO.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java
  src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
  src/main/java/com/springboot/enums/MedicationAssistant.java
  src/main/java/com/springboot/enums/WaterIntake.java
  src/test/java/com/springboot/api/controller/CounselCardControllerTest.java
  src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java
  src/test/java/com/springboot/api/controller/CounseleeAutocompleteControllerTest.java
  src/test/java/com/springboot/api/controller/CounseleeConsentControllerTest.java
  src/test/java/com/springboot/api/controller/CounseleeControllerTest.java
  src/test/java/com/springboot/api/service/AICounselSummaryServiceTest.java
Labels: D-3

#231 fix: :package: update package versions
  README.md
  build.gradle
  docs/README.md
Labels: D-3

#233 fix: :goal_net: fix enumerated error
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
Labels: bug, D-0

#234 fix: :goal_net: fix enumerated error (#233)
  src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
Labels: bug, D-0

#235 feat: configure management endpoints for actuator health and discovery
  src/main/resources/application.yml
Labels: D-2

#232 refactor: update counselee consent creation logic and optimize session query
  src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java
  src/main/java/com/springboot/api/counselcard/entity/CounselCard.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
  src/main/java/com/springboot/api/counselsession/controller/CounseleeConsentController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionListItem.java
  src/main/java/com/springboot/api/counselsession/entity/CounseleeConsent.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/repository/CounseleeConsentRepository.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/main/java/com/springboot/api/counselsession/service/CounseleeConsentService.java
  src/test/java/com/springboot/api/service/CounselSessionServiceTest.java
Labels: D-2
