Repository MediBird/caring-note-api-server, pull requests merged in 2025-06, with the labels that each got.

#258 feat: remove useless TestDataInitializer
  src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java
Labels: D-0

#259 feat: NoContentException 클래스 개선 및 AI 응답 파싱 유틸리티 클래스 추가
  src/main/java/com/springboot/api/common/exception/NoContentException.java
  src/main/java/com/springboot/api/common/util/AiResponseParseUtil.java
  src/main/java/com/springboot/api/counselsession/controller/AICounselSummaryController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectPreviousCounselSessionDetailRes.java
  src/main/java/com/springboot/api/counselsession/service/AICounselSummaryService.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
  src/test/java/com/springboot/api/common/util/AiResponseParseUtilTest.java
Labels: D-3

#261 feat: 내 정보 업데이트 및 비밀번호 변경 기능 추가
  src/main/java/com/springboot/api/counselor/controller/CounselorController.java
  src/main/java/com/springboot/api/counselor/dto/ChangePasswordReq.java
  src/main/java/com/springboot/api/counselor/dto/UpdateMyInfoReq.java
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
Labels: D-3

#262 refactor: 상담사 정보 업데이트 로직 간소화 및 Keycloak 사용자 삭제 로직 개선
  src/main/java/com/springboot/api/counselor/service/CounselorService.java
Labels: D-3

#263 refactor: 크론잡에서 진행 상태 상담 세션도 취소 처리하도록 변경
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
Labels: D-3

#264 refactor: ChangePasswordReq 클래스에서 현재 비밀번호 필드 제거
  src/main/java/com/springboot/api/counselor/dto/ChangePasswordReq.java
Labels: bug
