Repository MediBird/caring-note-api-server, pull requests merged in 2025-05, with the labels that each got.

#236 feature: add tus protocol
  Dockerfile
  build.gradle
  src/main/java/com/springboot/api/common/config/security/SecurityConfig.java
  src/main/java/com/springboot/api/common/util/FileUtil.java
  src/main/java/com/springboot/api/tus/config/TusConstant.java
  src/main/java/com/springboot/api/tus/config/TusProperties.java
  src/main/java/com/springboot/api/tus/controller/TusController.java
  src/main/java/com/springboot/api/tus/dto/response/TusFileInfoRes.java
  src/main/java/com/springboot/api/tus/entity/TusFileInfo.java
  src/main/java/com/springboot/api/tus/repository/TusFileInfoRepository.java
  src/main/java/com/springboot/api/tus/service/TusService.java
  src/main/resources/application.yml
Labels: D-2

#237 feature: add merge tus file
  src/main/java/com/springboot/api/common/config/security/SecurityConfig.java
  src/main/java/com/springboot/api/tus/config/TusConstant.java
  src/main/java/com/springboot/api/tus/config/TusProperties.java
  src/main/java/com/springboot/api/tus/controller/TusController.java
  src/main/java/com/springboot/api/tus/dto/response/TusFileInfoRes.java
  src/main/java/com/springboot/api/tus/entity/TusFileInfo.java
  src/main/java/com/springboot/api/tus/service/TusService.java
  src/main/resources/application.yml
Labels: D-3

#239 feat: :sparkles: add counsel session status filters
  src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SearchCounselSessionReq.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-3

#240 refactor: :recycle: refactor CounseleeConsentService to accept sessio…
  src/main/java/com/springboot/api/counselsession/controller/CounseleeConsentController.java
  src/main/java/com/springboot/api/counselsession/dto/counseleeconsent/AcceptConsentRes.java
  src/main/java/com/springboot/api/counselsession/dto/counseleeconsent/AddCounseleeConsentReq.java
  src/main/java/com/springboot/api/counselsession/dto/counseleeconsent/UpdateCounseleeConsentReq.java
  src/main/java/com/springboot/api/counselsession/dto/counseleeconsent/UpdateCounseleeConsentRes.java
  src/main/java/com/springboot/api/counselsession/service/CounseleeConsentService.java
  src/test/java/com/springboot/api/controller/CounseleeConsentControllerTest.java
Labels: D-3

#241 refactor: :recycle: refactor tus service
  src/main/java/com/springboot/api/common/util/FileUtil.java
  src/main/java/com/springboot/api/tus/config/TusConstant.java
  src/main/java/com/springboot/api/tus/config/TusHeaderKeys.java
  src/main/java/com/springboot/api/tus/config/TusProperties.java
  src/main/java/com/springboot/api/tus/controller/TusController.java
  src/main/java/com/springboot/api/tus/dto/response/TusFileInfoRes.java
  src/main/java/com/springboot/api/tus/entity/TusFileInfo.java
  src/main/java/com/springboot/api/tus/repository/TusFileInfoRepository.java
  src/main/java/com/springboot/api/tus/service/TusService.java
Labels: D-0

#245 fix: :bug: fix tus content type bug
  src/main/java/com/springboot/api/tus/controller/TusController.java
Labels: D-3

#244 refactor: :recycle: refactor UpdateCounseleeReq
  src/main/java/com/springboot/api/counselee/dto/UpdateCounseleeReq.java
  src/main/java/com/springboot/api/counselee/entity/Counselee.java
  src/test/java/com/springboot/api/controller/CounseleeControllerTest.java
  src/test/java/com/springboot/api/service/CounseleeServiceTest.java
Labels: D-3

#242 refactor: update counselor information handling in CounselSessionRepository
  src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
Labels: D-2

#243 refactor: update Counselor and SelectCounselSessionRes for improved structure and readability
  src/main/java/com/springboot/api/counselor/entity/Counselor.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
Labels: D-2

#246 refactor: :bug: delete files when error happend on merging
  src/main/java/com/springboot/api/common/util/FileUtil.java
  src/main/java/com/springboot/api/tus/controller/TusController.java
  src/main/java/com/springboot/api/tus/service/TusService.java
Labels: D-3

#254 feat: :sparkles: 이전 상담 내역 상세 조회 API 추가 및 서비스 로직 구현
  src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
  src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectPreviousCounselSessionDetailRes.java
  src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
Labels: D-3

#257 feat: renew consult counsel card
  src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java
  src/main/java/com/springboot/api/counselcard/dto/response/MainCounselBaseInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/MainCounselHealthInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/MainCounselIndependentLifeInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/MainCounselLivingInformationRes.java
  src/main/java/com/springboot/api/counselcard/dto/response/MainCounselRecord.java
  src/main/java/com/springboot/api/counselcard/dto/response/MainCounselRecordBuilder.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryCustom.java
  src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryImpl.java
  src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
Labels: D-3
